### ISSUE TITLE
is there any plan for documentation?

### ISSUE THREAD

**Issue by jinwei233** [timothypratley/reanimated#1]
awsome lib , but where can I find the docs?

**Comment by timothypratley** [comment]
Hi, thank you for your interest. I hope to get work on this some more on the way to and at Conj. In the meantime the examples source is the best place to look.

**Comment by timothypratley** [comment]
Added API docs and link from README
http://timothypratley.github.io/reanimated/codox/index.html

**Comment by timothypratley** [comment]
I've made the docs more complete, and added more live examples (linked from the README).
I think it's pretty much covered at this point.
