### ISSUE TITLE
Move fns that depend on react addons to another namespace?

### ISSUE THREAD

**Issue by iku000888** [timothypratley/reanimated#15]
Thanks for this library!

Because:
1. react-with-addons is deprecated, and there is some complexity in getting the dependency right
2. they are not the killer feature of this lib

I propose these two fns be migrated to another namespace.

https://github.com/timothypratley/reanimated/blob/master/src/reanimated/core.cljs#L385
https://github.com/timothypratley/reanimated/blob/master/src/reanimated/core.cljs#L389

I would be happy to submit a PR if that sounds good.

**Comment by timothypratley** [comment]
Hi Ikuru :)

Thank you for pointing this out! Yes I agree with you.
I'll happily accept a pull request.

Do you know if there is a replacement approach that does not use react-with-addons?
My preference would be to remove the dependency all together (no need to migrate them if they are deprecated)... but let me know if you think there is a reason not to.

Regards,
Timothy

**Comment by timothypratley** [comment]
I did a bit of reading and it looks like now if you want to use transition groups you can depend on it as a separate library:
https://reactcommunity.org/react-transition-group/

So I think we should remove those functions and the react-with-addons dependency completely. What do you think?

**Comment by iku000888** [comment]
I completely agree it is better to be removed completely!
Just was a bit hesitant, I guess :)

On a separate note, I did find this library nice to use
https://github.com/wikiwi/react-css-transition
