### ISSUE TITLE
Clojure 1.9 compatibility

### ISSUE THREAD

**Issue by tirkarthi** [timothypratley/reanimated#17]
Since Clojure 1.9 is stable and the current core.async version causes issues with Clojure 1.9 . This is fixed at clojure/core.async@2f87bc7 . Consider upgrading to core.async-0.3.442 or the latest core.async to support Clojure 1.9.

Thanks.

**Comment by timothypratley** [comment]
Thanks for the suggestion @tirkarthi, I've released [reanimated "0.6.1"] to address this issue. It updates to Clojure 1.9 and removes the core.async dependency (it was not needed).
