### ISSUE TITLE
support React Transition Group?

### ISSUE THREAD

**Issue by Frozenlock** [timothypratley/reanimated#2]
[React Transition Group](https://facebook.github.io/react/docs/animation.html#low-level-api-reacttransitiongroup)

It would be nice if reanimated could play nice with it, because it would open the way to making real mount/unmount animations.

**Comment by timothypratley** [comment]
I don't have a clear idea of how that would be implemented or used quite yet, but I'll try using it directly via interop and see if anything clicks. Thanks for the link.

**Comment by timothypratley** [comment]
Hi @Frozenlock 

Sorry for such a long delay.
I just got around to playing with React Transition Group.
It seems like it is fairly convenient to use.
I made an example here:
http://timothypratley.github.io/reanimated/#!/examples.core/css-transition-group-carousel-example

I haven't really written any code to make it happen, just using the react addons from within reagent... and it seems to work as advertised.

I would love to get some feedback on whether this is what you had in mind... or whether there is a use case I'm missing here.

@bendyorke Also I know you were looking into Transition Groups, what do you think of this approach?

**Comment by Frozenlock** [comment]
I just tried it and it works great!

I didn't have anything precise in mind, other than I wanted some simple way to 'hook' the animation to unmounting components. 

Do you know if it's possible to use it with a `reanimated` animation instead of a CSS one?

---

Edit: It looks like it's possible by using the low level API [ReactTransitionGroup](https://facebook.github.io/react/docs/animation.html#low-level-api-reacttransitiongroup)

Feel free to close this issue, unless you are still waiting for an input from bendyorke.

**Comment by timothypratley** [comment]
Hi. Yup I agree as you said the ReactTransitionGroup is the way to do this.
