### ISSUE TITLE
Don't animate pop-when initial state

### ISSUE THREAD

**Issue by Frozenlock** [timothypratley/reanimated#3]
`pop-when` will make an animation on components with their initial value.

This results in weird behavior, such as components appearing for a fraction of a second before disappearing when the page is loaded.

Shouldn't there be an option to avoid animation for the initial state of `condition`?

**Comment by timothypratley** [comment]
Hi Frozenlock,
Fixed in 0.1.3, thanks for spotting that :)
Please let me know if this resolves the problem.

**Comment by Frozenlock** [comment]
It still seems to behave the same way with the new version. :-(

**Comment by timothypratley** [comment]
Sorry to hear that. Can you post a snippet of the code you are using? I'll take a closer look at this tonight.

**Comment by Frozenlock** [comment]
Sure.

It's a little notification component:

![image](https://cloud.githubusercontent.com/assets/1152041/11218059/54c8b592-8d21-11e5-809c-ce8f3aad78f7.png)

Here's the code:

``` clj
(ns cea.notify
  (:require [reagent.core :as r]
            [timothypratley.reanimated.core :as anim]))


(def notify-type-classes {:success "alert-success"
                          :info "alert-info"
                          :warning "alert-warning"
                          :danger "alert-danger"})

(def show-notify? (r/atom false))

(def notify-content (r/atom [:div]))

(def current-notify-type (r/atom :success))

(defn notify-body
  "Basic notify message"
  []
  [:div {:style {:top 0
                 :right 0
                 :position "fixed"
                 :margin 5
                 :z-index 1050}}
  [anim/pop-when @show-notify?
     [:div {:class (str "alert "(get notify-type-classes @current-notify-type "alert-success"))}
      [anim/timeout #(reset! show-notify? false) 10000]
      [:span {:style {:display "inline-block"}} @notify-content]
      " "
      [:span.glyphicon.glyphicon-remove
       {:on-click #(reset! show-notify? false)
        :style {:cursor "pointer"}}]]]])

(defn notify!
  "Content can be a string or a Reagent component.
  Optional argument 'notify-type' can be one of the following:
  - :success
  - :info
  - :warning
  - :danger"
  ([content] (notify! content nil))
  ([content notify-type]
   (reset! notify-content content)
   (reset! current-notify-type notify-type)
   (reset! show-notify? true)))

```

**Comment by timothypratley** [comment]
@Frozenlock Thank you for the code, nice notifier.
I made a test repository here:
https://github.com/timothypratley/reanimated-test
Using 0.1.3 and couldn't reproduce the behavior you described.
Please check your project file and try `lein clean` and rebuilding to see if perhaps some stale code is the problem?
If you are still seeing the behavior, could you please checkout https://github.com/timothypratley/reanimated-test
`lein figwheel` and open `localhost:3449` and see if the behavior is there for you?

**Comment by Frozenlock** [comment]
Your repo works fine. :+1: 

I doubled check to make sure I was doing `lean clean` and indeed I was.

_However_, turns out that the js files from devcards are NOT deleted with a `lean clean`. (They are not generated in the same directory as the vanilla fighweel.)

Thanks for your support.

**Comment by timothypratley** [comment]
Ok great :)

I think you can control the clean behavior in your project.clj with

```
  :clean-targets ^{:protect false} ["js/compiled/out"
                                    "js/compiled/out-dev"
                                    :target-path]

```
